config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :foods

  resources :home

  root :to => 'home#index'
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :user
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :foods
  has_many :exercises
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def new
    @food = Food.new
  end

  def create
    user = current_user
    @food = user.foods.new(food_params)
    if @food.save
      respond_to do |format|
        format.html { redirect_to root }
        format.js
      end
    else
      # Add alert for missing text here
      flash[:alert] = 'Please supply text for the new food.'
    end
  end

  private
  def food_params
    params.require(:food).permit(:name, :calories)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/foods/_form.html.erb
<div id="add-food-form">
  <%= form_for @food, remote: true do |f| %>

    <%= f.label :name, 'Food' %>
    <%= f.text_field :name %>
    <%= f.label :calories, 'Calories' %>
    <%= f.number_field :calories %>

    <%= f.submit 'Submit' %>
  <% end %>
</div>

app/views/foods/create.js.erb
$('form').remove();
$('#food-list').append('<li><%= @food.name %></li>')
$('#food-div a').show()

app/views/foods/new.js.erb
$('#food-div a').hide()
$('#food-form-div').append("<%= j render 'form' %>")

app/views/home/index.html.erb
<h1>Homepage (No typos allowed)</h1>

<div id="food-div">
  <h4>Calories Consumed</h4>
  <p><%= link_to "Enter Food", new_food_path, class: 'btn btn-success', remote: true %></p>
</div>
<div id="food-form-div">

</div>
<div>
  <ul id="food-list">
    <% current_user.foods.each do |food| %>
      <li><%= food.name %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealthTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Health Tracker</a>
    </div>
    <div class="collapse navbar-collapse">

      <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
  </div>
</nav>



  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>


  <%= yield %>
</body>
</html>